Repository hassio-addons/addon-spotify-connect, pull requests merged in 2022-01, with the labels that each got.

#163 Added Hungarian translation
  spotify/translations/hu.yaml
Labels: in-progress, translations

#165 :fireworks: Updates maintenance/license year to 2022
  LICENSE.md
  README.md
  spotify/.README.j2
  spotify/DOCS.md
Labels: maintenance

#166 ⬆️ Upgrades add-on base image to 11.0.1
  spotify/Dockerfile
  spotify/build.yaml
Labels: dependencies
