Repository hassio-addons/addon-spotify-connect, pull requests merged in 2022-06, with the labels that each got.

#174 ⬆️ Upgrades librespot to 0.4.1
  spotify/Dockerfile
Labels: minor, dependencies

#176 :books: Use new My Home Assistant link format
  spotify/DOCS.md
Labels: documentation

#175 :broom: Clean up unneeded command line params
  spotify/Dockerfile
Labels: maintenance

#177 Create it.yaml (italian translation)
  spotify/translations/it.yaml
Labels: translations

#178 🌎 Italian translation updates
  spotify/translations/it.yaml
Labels: translations
