Repository hassio-addons/addon-spotify-connect, pull requests merged in 2025-02, with the labels that each got.

#281 Upgrade base to 17.1.1 and resolve problems with building librespot 0.6.0
  spotify/Dockerfile
  spotify/build.yaml
Labels: major, dependencies

#254 Add librespot autoplay option
  spotify/DOCS.md
  spotify/config.yaml
  spotify/rootfs/etc/services.d/spotifyd/run
  spotify/translations/en.yaml
Labels: new-feature

#282 :fireworks: Update copyright year to 2025 in license and documentation files
  LICENSE.md
  README.md
  spotify/.README.j2
  spotify/DOCS.md
Labels: maintenance

#276 Add librespot initial-volume option
  spotify/DOCS.md
  spotify/config.yaml
  spotify/rootfs/etc/services.d/spotifyd/run
  spotify/translations/en.yaml
  spotify/translations/hu.yaml
  spotify/translations/it.yaml
Labels: new-feature

#286 Fix problem with declaring bash variable with dash
  spotify/DOCS.md
  spotify/config.yaml
  spotify/rootfs/etc/services.d/spotifyd/run
  spotify/translations/en.yaml
  spotify/translations/hu.yaml
  spotify/translations/it.yaml
Labels: bugfix

#287 fix: autoplay
  spotify/rootfs/etc/services.d/spotifyd/run
Labels: bugfix

#291 Remove unneeded volume checks
  spotify/config.yaml
  spotify/rootfs/etc/services.d/spotifyd/run
Labels: refactor
